package certifications

var DefaultCertifications = []Certification{
	{
		ID:          "generalist",
		Title:       "Generalist",
		RoleKey:     "generalist",
		Description: "Complete all published concepts across TraceLab libraries.",
		ImagePath:   "/certifications/tl_software_engineer.png",
		SortOrder:   5,
		Active:      true,
	},
	{
		ID:          "backend-engineer",
		Title:       "Backend Engineer",
		RoleKey:     "backend_engineer",
		Description: "Build reliable APIs, data services, and distributed systems.",
		ImagePath:   "/certifications/tl_backend_engineer.png",
		SortOrder:   10,
		Active:      true,
	},
	{
		ID:          "software-engineer",
		Title:       "Software Engineer",
		RoleKey:     "software_engineer",
		Description: "Ship end-to-end product features across frontend, backend, and data boundaries.",
		ImagePath:   "/certifications/tl_software_engineer.png",
		SortOrder:   20,
		Active:      true,
	},
	{
		ID:          "data-engineer",
		Title:       "Data Engineer",
		RoleKey:     "data_engineer",
		Description: "Design data pipelines, storage systems, and analytics-ready platforms.",
		ImagePath:   "/certifications/tl_data_engineer.png",
		SortOrder:   30,
		Active:      true,
	},
	{
		ID:          "frontend-engineer",
		Title:       "Frontend Engineer",
		RoleKey:     "frontend_engineer",
		Description: "Craft high-quality user interfaces and performant web application experiences.",
		ImagePath:   "/certifications/tl_frontend_engineer.png",
		SortOrder:   40,
		Active:      true,
	},
	{
		ID:          "platform-engineer",
		Title:       "Platform Engineer",
		RoleKey:     "platform_engineer",
		Description: "Create internal platforms, developer tooling, and cloud delivery foundations.",
		ImagePath:   "/certifications/tl_platform_engineer.png",
		SortOrder:   50,
		Active:      true,
	},
	{
		ID:          "network-engineer",
		Title:       "Network Engineer",
		RoleKey:     "network_engineer",
		Description: "Architect resilient connectivity, traffic routing, and secure network operations.",
		ImagePath:   "/certifications/tl-network-engineer.png",
		SortOrder:   60,
		Active:      true,
	},
	{
		ID:          "expert",
		Title:       "TraceLab Expert",
		RoleKey:     "expert",
		Description: "Reserved for learners who complete all published TraceLab material.",
		ImagePath:   "/certifications/tl_expert.png",
		SortOrder:   999,
		Active:      true,
	},
}
